ProductShop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using ProductShop.ActionFilters;
using ProductShop.Data;
using ProductShop.Data.Entities;
using ProductShop.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace ProductShop.Controllers
{
    [Internationalization]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        // доступ до даних, через обєкт IStringLocalizer
        private readonly IStringLocalizer<HomeController> _localizer;
        public EFAppContext _context { get; set; }

        public HomeController(ILogger<HomeController> logger,
            IStringLocalizer<HomeController> localizer,
            EFAppContext context)
        {
            _logger = logger;
            _context = context;
            // ініціалізація обєкта IStringLocalizer
            _localizer = localizer;
        }
        #region Default
        public IActionResult Index()
        {
            ViewBag.Email = _localizer["Email"];
            return View(_context.Products.Include(x => x.Images).Select(x => new ProductViewModel { 
                Name = x.Name,
                Price = x.Price,
                Id = x.Id,
                Images = x.Images.Select(x => new ProductImageItemViewModel { 
                Path = x.Name,
                }).ToList()
            }).ToList());
        }

        //[HttpGet]
        //public IActionResult SetLanguage(string culture, string returnUrl)
        //{
        //    Response.Cookies.Append(
        //        CookieRequestCultureProvider.DefaultCookieName,
        //        CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
        //        new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
        //    );
        //    //HttpContext.Session.SetString("SetLanguage", culture);

        //    if (!string.IsNullOrEmpty(returnUrl))
        //        return LocalRedirect(returnUrl);
        //    return RedirectToAction("Index");
        //}

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        #endregion

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(ProductAddViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Дані введено не коректно!");
                return View(model);

            }

            var product = new Product();
            product.Name = model.Name;
            product.Price = model.Price;
            product.Images = new List<ProductImage>();
            _context.Products.Add(product);
            _context.SaveChanges();

            string dirPath = Path.Combine(Directory.GetCurrentDirectory(), "images");

            if (model.Images != null)
            {
                foreach (var newImages in model.Images)
                {
                    string ext = Path.GetExtension(newImages.FileName);
                    string fileName = Path.GetRandomFileName() + ext;

                    string filePath = Path.Combine(dirPath, fileName);
                    using (var stream = System.IO.File.Create(filePath))
                    {
                        newImages.CopyTo(stream);
                    }

                    _context.ProductImages.Add(new Data.Entities.ProductImage
                    {
                        Name = fileName,
                        ProductId = product.Id
                    });
                }
            }

            _context.SaveChanges();


            return RedirectToAction("Index", "Home");
        }


        [HttpGet]
        public IActionResult Edit() 
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Edit(ProductEditViewModel model) 
        {
            if (!ModelState.IsValid) { 
                ModelState.AddModelError("", "Дані введено не коректно!");
                return View(model);
            
            }

            if (model.Id == 0) 
            {
                ModelState.AddModelError("", "Оберіть продукт видалення!");
                return View(model);
            }

            var product = _context.Products.Include(x => x.Images).FirstOrDefault(x => x.Id == model.Id);
            if (product != null) 
            {
                string dirPath = Path.Combine(Directory.GetCurrentDirectory(), "images");
                product.Name = model.Name;
                product.Price = model.Price;
                if (model.deletedImages != null) { 
                    foreach (var delProduct in model.deletedImages) 
                {
                    var delProductImage = product.Images.SingleOrDefault(x => delProduct.Contains(x.Name));
                    string imgPath = Path.Combine(dirPath, delProductImage.Name);
                    if (System.IO.File.Exists(imgPath)) 
                    {
                        System.IO.File.Delete(imgPath);
                    }
                    _context.ProductImages.Remove(delProductImage);
                }
                }
                if (model.Images != null) 
                {
                    foreach (var newImages in model.Images)
                {
                    string ext = Path.GetExtension(newImages.FileName);
                    string fileName = Path.GetRandomFileName() + ext;

                    string filePath = Path.Combine(dirPath, fileName);
                    using (var stream = System.IO.File.Create(filePath)) 
                    {
                        newImages.CopyTo(stream);
                    }

                    _context.ProductImages.Add(new Data.Entities.ProductImage { 
                        Name = fileName,
                        ProductId = product.Id
                    });
                }
                }

                _context.SaveChanges();
            }
            else {
                ModelState.AddModelError("", "Помилка коду! Зверніться до сервісного центру!");
                return View(model);
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult GetData(int id) 
        {
            var product = _context.Products.Include(x => x.Images).FirstOrDefault(x => x.Id == id);
            ProductViewModel model = new ProductViewModel { 
            Id = product.Id,
            Name = product.Name,
            Price = product.Price,
            Images = product.Images.Select(x => new ProductImageItemViewModel { 
                Path = x.Name
            }).ToList()
            };
            return Ok(JsonConvert.SerializeObject(model));
        }


        [HttpPost]
        public IActionResult Delete(int id) 
        {
            var product = _context.Products.FirstOrDefault(x => x.Id == id);
            if (product != null)
            {
                List<ProductImage> images = _context
                    .ProductImages.Where(x => x.ProductId == product.Id).ToList();

                foreach (var image in images)
                {
                    string imageName = Path.Combine(Directory.GetCurrentDirectory(), "images", image.Name);
                    if (System.IO.File.Exists(imageName))
                    {
                        System.IO.File.Delete(imageName);
                    }

                    _context.ProductImages.Remove(image);
                }
                _context.SaveChanges();

                _context.Products.Remove(product);
                _context.SaveChanges();
            }
            return Ok();
        }
        
    }

}

ProductShop/ViewComponents/ShowProductViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ProductShop.Data;
using ProductShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProductShop.ViewComponents
{
    public class ShowProductViewComponent : ViewComponent
    {
        public EFAppContext _context { get; set; }
        public ShowProductViewComponent(EFAppContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync() 
        {
            return await Task.Run(() => {
                return View("_ShowProduct", _context.Products.Select(x => new ProductOptionViewModel { 
                    Id = x.Id,
                    Name = x.Name
                }).ToList());
            });
        }
    }
}

ProductShop/Views/Home/Add.cshtml
@model ProductAddViewModel

<div class="container">
    <div class="row">
        <div class="col-md-8 offset-2">
            <h2 class="text-center">Додати товар</h2>

            <form method="post" enctype="multipart/form-data" asp-controller="Home" asp-action="Add">

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input class="form-control" asp-for="Name" placeholder="Назва" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price"></label>
                    <input class="form-control" asp-for="Price" placeholder="Ціна" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <div class="row mt-3" id="imageMainBlock">
                        <div class="col-2">
                            <img src="/images/btnaddimage.jpg" 
                                 width="60" 
                                 height="60" 
                                 id="btnAddImage"
                                 style="cursor: pointer"/>
                        </div>
                    </div>
                </div>

                <div class="form-group mt-2">
                    <input type="submit" class="btn btn-success" value="Додати" />
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/lib/axios/axios.min.js"></script>
    <script>
        $(function () {
            
            var inputId = 1;

            //Додати фотку в список фото (нову фотку)
            $addbtnimage = $("#btnAddImage");
            $addbtnimage.on("click", function () {
                //блок, який містить усі фотки
                var $blockImages = $("#imageMainBlock");
                //Іd - інтпута для вибору файла фото
                var idName = "imageId" + inputId;
                var $inputAdd = $(`
                        <input type="file"
                        id="${idName}" 
                        class="d-none added"
                        name="Images"
                        multiple/>`);

                //додаємо інпут в дом дерево - там де знаходяться усі елементи фото
                $blockImages.prepend($inputAdd);
                //ми додали наш інпут для файлу в дом, тепер мона його отримати
                var input = document.getElementById(idName);
                //Клікаємо по інтпуту
                input.click();

                //якщо ми обрали, якись файл
                input.onchange = function (e) {
                    
                    ///ми отримуємо список файлі, що обрали
                    ///event.target
                    var files = e.target.files;
                    for (var i = 0; i < files.length; i++) {
                        //добавляємо іконку х - для видалення
                        var $deleteIcon = $(`
                                <span class="text-danger align-top" style="cursor: pointer">
                                    <i class="fas fa-times"></i>
                                </span>`);

                        //створюємо дів, для збереження фото
                        $newDiv = $(`<div class="col-2 added" name="${files[i]["name"]}">
                            <img src="${URL.createObjectURL(files[i])}" class="m-2" width="60" height="60"/>
                        </div>`);
                        //в дів добавляємо хрестик
                        $newDiv.append($deleteIcon);

                        //в самий головний дів додаємо хрестик і фотку
                        $blockImages.prepend($newDiv);

                        //Обробник видалити фотку із списку
                        $deleteIcon.on("click", function (e) {
                            //Для того, щоб із інтпута типу file можна було видаляти файлики
                            var fileList = new DataTransfer();
                            //Находимо головний дів для блоку
                            let $div = $(e.target).closest("div");
                            $div.remove();
                            //видаляємо з інтпута типу файл, файл до якого віносилася фотографія
                            let fileInputImages = document.getElementById(idName);
                            $(fileInputImages.files).each(index => {
                                
                                if (fileInputImages.files[index]["name"] != $div.attr("name")) {
                                    fileList.items.add(fileInputImages.files[index]);
                                };
                            });
                            //перезаписуємо у відповідному інпуті фотки, щоб вони не відпавилися на север.
                            fileInputImages.files = fileList.files;
                            //Якщо в інпуті файл відсутні фотки, то ми його грохаємо
                            if (fileList.files.length == 0)
                                $(`#${idName}`).remove();
                        });

                        
                    }
                }

                //змінюємо іd для ідентифікатора інпута
                inputId++;
            });
        });
    </script>
}

ProductShop/Views/Home/Edit.cshtml
@model ProductEditViewModel

<div class="container">
    <div class="row">
        <div class="col-md-8 offset-2">
            <h2 class="text-center">Редагувати товар</h2>

            <form method="post" enctype="multipart/form-data" asp-controller="Home" asp-action="Edit">
                @*<div class="form-group mb-3">
                    <label asp-for="SelectGroup"></label>
                    @await Component.InvokeAsync("ShowProduct")
                </div>*@
                <input asp-for="Id" class="d-none" />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input class="form-control" asp-for="Name" placeholder="Назва" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price"></label>
                    <input class="form-control" asp-for="Price" placeholder="Ціна" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <div class="row mt-3" id="imageMainBlock">
                        <div class="col-2">
                            <img src="/images/btnaddimage.jpg" 
                                 width="60" 
                                 height="60" 
                                 id="btnAddImage"
                                 style="cursor: pointer"/>
                        </div>
                    </div>
                </div>

                <div class="form-group mt-2">
                    <input type="submit" class="btn btn-success" value="Змінити" />
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/lib/axios/axios.min.js"></script>
    <script src="~/lib/select2/js/i18n/uk.min.js"></script>
    <script src="~/lib/select2/js/select2.full.min.js"></script>
    <script>
        $(function () {
            $(".selection").select2();
            var id = 1;
            var inputId = 1;
            //  З URL отримуємо id товару якого будемо міняти
            var idUrl = new URLSearchParams(window.location.search).get("idproduct");
            console.log("id = ", idUrl);

            //  Із сервера по ідентифікатору отримуємо товар який редагуємо
            axios.get('/api/Product/get/' + idUrl)
                .then(result => {
                    //  Якщо запит був успішний то отримуємо результат
                    console.log(result);
                    var data = result.data; //  Результат записуємо в дату
                    $("input#Name").val(data.name); //  В інпут нейм записуємо назву продукта
                    $("input#Price").val(data.price); //  В інпут нейм записуємо ціну продукта
                    $("input#Id").val(data.id); //  В інпут нейм записуємо ід продукта
                    var images = data.images; //  В інпут нейм записуємо список фоток продукта


                            var idName = "image" + id;
                    //  Циклом передираєм усі фотографії
                    for (var i = 0; i < images.length; i++) {
                                // Ствоерння іконку видалення
                                var $deleteIcon = $(`<span class="text-danger align-top">
                                <i class="fas fa-times"></i></span>`);
                        // Оброблення події видалення елемента фотграфії
                                $deleteIcon.on("click", function (e) {
                                    let $div = $(e.target).closest("div");
                                    $div.remove();
                                    // додавання інпута який містить посилання нв фотографію яку видалити
                                    $("#imageMainBlock").prepend(`<input type="hidden"
                                    value="${$div.find('img').attr("src")}" name="deletedImages"/>`);
                                });

                        // Створюємо блок який відображає фотографію
                                $blockInput = $(`<div class="col-md-2 d-flex">
                                        <img src="/images/${images[i].path}" width="60" height="60" class="m-2"/>
                                    </div>`);
                                $blockInput.append($deleteIcon);

                                id++;
                        // Додає одну фотографію в спеціальний блок з назвою imageMainBlock там де містяться усі фотграфії редаговано елемента
                                $("#imageMainBlock").prepend($blockInput);
                            }
                        })
                .catch(error => {
                            alert(error);
                        });

        ///var $select = $("#SelectGroup");
        ///$select.on("change", function () {
        ///    $divsAdded = $("#imageMainBlock .added");
        ///    $divsAdded.each(index => {
        ///        $divsAdded[index].remove();
        ///    });
        ///    $("input#Id").val("0");
        ///    if ($select.val() != 0) {
        ///        axios.post('/Home/GetData/' + $select.val())
        ///            .then(result => {
        ///                var data = JSON.parse(JSON.stringify(result["data"]));
        ///                $("input#Name").val(data["Name"]);
        ///                $("input#Price").val(data["Price"]);
        ///                $("input#Id").val(data["Id"]);
        ///                var images = data["Images"];
        ///              
        ///
        ///                var idName = "image" + id;
        ///              
        ///                for (var i = 0; i < images.length; i++) {
        ///                    var $deleteIcon = $(`<span class="text-danger align-top">
        ///                    <i class="fas fa-times"></i></span>`);
        ///
        ///                    $deleteIcon.on("click", function (e) {
        ///                        let $div = $(e.target).closest("div");
        ///                        $div.remove();
        ///                        $("#imageMainBlock").prepend(`<input class="d-none added" 
        ///                        value="${$div.find('img').attr("src")}" name="deletedImages"/>`);
        ///                    });
        ///
        ///
        ///                    $blockInput = $(`<div class="col-md-2 added d-flex">
        ///                            <img src="/images/${images[i]["Path"]}" width="60" height="60" class="m-2"/>
        ///                        </div>`);
        ///                    $blockInput.append($deleteIcon);
        ///
        ///                    id++;
        ///
        ///                    $("#imageMainBlock").prepend($blockInput);
        ///                }
        ///            })
        ///            .catch(error => {
        ///                alert(error);
        ///            });
        ///    }
        ///
        ///});

            //Додати фотку в список фото (нову фотку)
            $addbtnimage = $("#btnAddImage");
            $addbtnimage.on("click", function () {
                //блок, який містить усі фотки
                var $blockImages = $("#imageMainBlock");
                //Іd - інтпута для вибору файла фото
                var idName = "imageId" + inputId;
                var $inputAdd = $(`
                        <input type="file"
                        id="${idName}" 
                        class="d-none added"
                        name="Images"
                        multiple/>`);

                //додаємо інпут в дом дерево - там де знаходяться усі елементи фото
                $blockImages.prepend($inputAdd);
                //ми додали наш інпут для файлу в дом, тепер мона його отримати
                var input = document.getElementById(idName);
                //Клікаємо по інтпуту
                input.click();

                //якщо ми обрали, якись файл
                input.onchange = function (e) {
                    
                    ///ми отримуємо список файлі, що обрали
                    ///event.target
                    var files = e.target.files;
                    for (var i = 0; i < files.length; i++) {
                        //добавляємо іконку х - для видалення
                        var $deleteIcon = $(`
                                <span class="text-danger align-top" style="cursor: pointer">
                                    <i class="fas fa-times"></i>
                                </span>`);

                        //створюємо дів, для збереження фото
                        $newDiv = $(`<div class="col-2 added" name="${files[i]["name"]}">
                            <img src="${URL.createObjectURL(files[i])}" class="m-2" width="60" height="60"/>
                        </div>`);
                        //в дів добавляємо хрестик
                        $newDiv.append($deleteIcon);

                        //в самий головний дів додаємо хрестик і фотку
                        $blockImages.prepend($newDiv);

                        //Обробник видалити фотку із списку
                        $deleteIcon.on("click", function (e) {
                            //Для того, щоб із інтпута типу file можна було видаляти файлики
                            var fileList = new DataTransfer();
                            //Находимо головний дів для блоку
                            let $div = $(e.target).closest("div");
                            $div.remove();
                            //видаляємо з інтпута типу файл, файл до якого віносилася фотографія
                            let fileInputImages = document.getElementById(idName);
                            $(fileInputImages.files).each(index => {
                                
                                if (fileInputImages.files[index]["name"] != $div.attr("name")) {
                                    fileList.items.add(fileInputImages.files[index]);
                                };
                            });
                            //перезаписуємо у відповідному інпуті фотки, щоб вони не відпавилися на север.
                            fileInputImages.files = fileList.files;
                            //Якщо в інпуті файл відсутні фотки, то ми його грохаємо
                            if (fileList.files.length == 0)
                                $(`#${idName}`).remove();
                        });

                        
                    }
                }

                //змінюємо іd для ідентифікатора інпута
                inputId++;
            });
        });
    </script>
}

ProductShop/Views/Home/Index.cshtml
@model List<ProductViewModel>
@using Microsoft.Extensions.Localization
@using ProductShop.Controllers
@inject IStringLocalizer<HomeController> Localizer

@{
    ViewData["Title"] = "Home Page";
}

<div class="container">

    <div class="row">

        <div class="offset-2 col-8">
            <h1 class="text-center">@Localizer["Email"]</h1>
            <a asp-action="Add" class="btn btn-success mb-3">@Localizer["Add"]</a>

            <table class="table table-bordered table-striped">
                <thead class="table-dark">
                    <tr>
                        <th scope="col">@Localizer["Name"]</th>
                        <th scope="col">@Localizer["Price"]</th>
                        <th scope="col">@Localizer["Photo"]</th>
                        <th scope="col">@Localizer["Tools"]</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var product in Model)
                    {
                        <tr>
                            <td scope="row">@product.Name</td>
                            <td>₴ @product.Price</td>
                            <td>
                                <div class="container-fluid">
                                    <div class="row">
                                        @foreach (var image in product.Images)
                                        {
                                            <div class="col-2 ms-2">
                                                <img src="/images/@image.Path" width="100%" />
                                            </div>
                                        }
                                    </div>
                                </div>
                            </td>
                            <td>
                                <div class="container d-flex align-items">

                                    <div class="mx-auto my-auto">
                                        <span class="text-danger deleteitem" data-element="@product.Id"><i class="fas fa-trash-alt fa-lg"></i></span>
                                    </div>
                                    <div class="mx-auto my-auto">
                                        <a asp-controller="Home" asp-action="Edit" asp-route-idproduct="@product.Id"
                                           class="text-danger deleteitem"><i class="fas fa-edit fa-lg"></i></a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/lib/axios/axios.min.js"></script>
    <script>
        $(function () {
            $(".deleteitem").on("click", function (e) {
                //console.log(e.target);
                var id = $(e.target).closest("span").attr("data-element");
                axios.post(`/Home/Delete/${id}`)
                    .then(result => {
                        return new Promise((resolve, reject) => {
                            var $divItem = $(e.target).closest("tr");
                            $divItem.remove();

                            resolve();
                        });
                    });
            });
        });
    </script>

}